name: deploy

on:
  push:
    branches:
      - main

env:
  BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
  CHANNEL_NAME: ${{ vars.CHANNEL_NAME }}
  LOG_LEVEL: ${{ vars.LOG_LEVEL }}
  TORIKI_COMMAND: ${{ vars.TORIKI_COMMAND }}

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - shell: bash
        run: |
          touch .env
          cat <<EOF > .env
          BOT_TOKEN=${BOT_TOKEN}
          CHANNEL_NAME=${CHANNEL_NAME}
          LOG_LEVEL=${LOG_LEVEL}
          TORIKI_COMMAND=${TORIKI_COMMAND}
          EOF
      - name: deploy
        run: docker compose up -d --force-recreate
