name: deploy

on:
  push:
    branches:
      - main

env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANNEL_NAME: ${{ vars.CHANNEL_NAME }}
  LOG_LEVEL: ${{ vars.LOG_LEVEL }}
  TORIKI_COMMAND: ${{ vars.TORIKI_COMMAND }}

jobs:
  deploy:
    name: deploy
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        run: docker compose up -d --force-recreate
